### ISSUE TITLE
Remove ANT stuff

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/protege-server#3]
The project contains some old ANT files (build.xml).

**Comment by matthewhorridge** [comment]
The comment on the Ant script is ```Helper scripts for the maven build```  
@stdotjohn if you have a moment, any background info on why ant is involved would be much appreciated.

**Comment by lonniev** [comment]
Need to update the wiki documentation that the ant targets for run and debug are no more. Instead, it seems, there are the run.sh and debug.sh startup scripts.

**Comment by csnyulas** [comment]
@lonniev  can you provide links to the wiki entries that needs to be updates?

**Comment by rsgoncalves** [comment]
The wiki documentation that mentions ant targets is for v2.x of the server, which worked for Protege 4. The new server (v3.x for Protege 5) will be documented in the wiki when the new version is released, and that documentation will reflect the fact that one now uses the run.sh and debug.sh scripts directly.

Meanwhile, the cleanup of Ant stuff has been done, and since this issue wasn't meant for missing documentation on unreleased software I'm re-closing it.

**Comment by lonniev** [comment]
No problem. I meant to post you back the wiki link where the Ant stuff is mentioned. I did the cut half of that task and got distracted before doing the paste.

As you remark, you already found it.

For now, I’d just clarify on the READMEs for 5.x that links to content may be to older 3.x and 4.x as placeholders.

http://protegewiki.stanford.edu/wiki/Protege_4_Development_Environment#Install_and_Run_From_Svn



-- 
Lonnie VanZandt
303-900-3048

On 05 April 2016 at 22:40:26, Rafael Gonçalves (notifications@github.com) wrote:

The wiki documentation that mentions ant targets is for v2.x of the server, which worked for Protege 4. The new server (v3.x for Protege 5) will be documented in the wiki when the new version is released, and that documentation will reflect the fact that one now uses the run.sh and debug.sh scripts directly.

Meanwhile, the cleanup of Ant stuff has been done, and since this issue wasn't meant for missing documentation on unreleased software I'm re-closing it.
